### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by ReichYang** [amansrivastava17/embedding-as-service#71]
```
Collecting embedding-as-service
  Using cached embedding_as_service-2.0.1-py2.py3-none-any.whl (140 kB)
Collecting smart-open==1.8.4
  Using cached smart_open-1.8.4.tar.gz (63 kB)
Collecting bert-tensorflow==1.0.1
  Using cached bert_tensorflow-1.0.1-py2.py3-none-any.whl (67 kB)
Collecting embedding-as-service
  Using cached embedding_as_service-2.0.0-py3-none-any.whl (140 kB)
  Using cached embedding_as_service-1.6.0-py3-none-any.whl (138 kB)
  Using cached embedding_as_service-1.5.0-py3-none-any.whl (137 kB)
Collecting tqdm==4.32.2
  Using cached tqdm-4.32.2-py2.py3-none-any.whl (50 kB)
Collecting requests==2.21.0
  Using cached requests-2.21.0-py2.py3-none-any.whl (57 kB)
Collecting embedding-as-service
  Using cached embedding_as_service-1.4.0-py3-none-any.whl (137 kB)
  Using cached embedding_as_service-1.3.0-py3-none-any.whl (130 kB)
  Using cached embedding_as_service-1.0.0-py3-none-any.whl (129 kB)
  Using cached embedding_as_service-0.9.0-py3-none-any.whl (129 kB)
  Using cached embedding_as_service-0.8.0-py3-none-any.whl (129 kB)
  Using cached embedding_as_service-0.7.0-py3-none-any.whl (128 kB)
  Using cached embedding_as_service-0.6.0-py3-none-any.whl (128 kB)
  Using cached embedding_as_service-0.5.0-py3-none-any.whl (128 kB)
  Using cached embedding_as_service-0.4.0-py3-none-any.whl (127 kB)
Collecting keras==2.2.4
  Using cached Keras-2.2.4-py2.py3-none-any.whl (312 kB)
Collecting numpy==1.16.4
  Using cached numpy-1.16.4.zip (5.1 MB)
Collecting embedding-as-service
  Using cached embedding_as_service-0.3.0-py3-none-any.whl (127 kB)
  Using cached embedding_as_service-0.2.0-py3-none-any.whl (127 kB)
  Using cached embedding_as_service-0.1.0-py3-none-any.whl (127 kB)
  Using cached embedding_as_service-0.0.9-py3-none-any.whl (127 kB)
  Using cached embedding_as_service-0.0.8-py3-none-any.whl (127 kB)
  Using cached embedding_as_service-0.0.7-py3-none-any.whl (127 kB)
  Using cached embedding_as_service-0.0.6-py3-none-any.whl (125 kB)
  Using cached embedding_as_service-0.0.5-py3-none-any.whl (125 kB)
  Using cached embedding_as_service-0.0.4-py3-none-any.whl (125 kB)
  Using cached embedding_as_service-0.0.3.tar.gz (101 kB)
    ERROR: Command errored out with exit status 1:
     command: /Users/yukun/Documents/test/embedding/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/5v/ch_dxl5912d4b01mmx58fspc0000gq/T/pip-install-73u8bfbs/embedding-as-service_b92c8b6f06314513b9c0f503051c3bab/setup.py'"'"'; __file__='"'"'/private/var/folders/5v/ch_dxl5912d4b01mmx58fspc0000gq/T/pip-install-73u8bfbs/embedding-as-service_b92c8b6f06314513b9c0f503051c3bab/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/5v/ch_dxl5912d4b01mmx58fspc0000gq/T/pip-pip-egg-info-bo11tpx2
         cwd: /private/var/folders/5v/ch_dxl5912d4b01mmx58fspc0000gq/T/pip-install-73u8bfbs/embedding-as-service_b92c8b6f06314513b9c0f503051c3bab/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/5v/ch_dxl5912d4b01mmx58fspc0000gq/T/pip-install-73u8bfbs/embedding-as-service_b92c8b6f06314513b9c0f503051c3bab/setup.py", line 6, in <module>
        with open('requirements.txt') as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/8e/db/6d4a90013dcaffce09a03ac33377fb7748ecc66bb87b71bf66e012dacb98/embedding_as_service-0.0.3.tar.gz#sha256=1d1acca51129707dee93cb47b43d67297c3ecfb0ae1e2d3f574c92bf0920320f (from https://pypi.org/simple/embedding-as-service/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Using cached embedding_as_service-0.0.2.tar.gz (1.3 kB)
    ERROR: Command errored out with exit status 1:
     command: /Users/yukun/Documents/test/embedding/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/5v/ch_dxl5912d4b01mmx58fspc0000gq/T/pip-install-73u8bfbs/embedding-as-service_13c5a0df862943ec82ce0f3c3d1bcad2/setup.py'"'"'; __file__='"'"'/private/var/folders/5v/ch_dxl5912d4b01mmx58fspc0000gq/T/pip-install-73u8bfbs/embedding-as-service_13c5a0df862943ec82ce0f3c3d1bcad2/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/5v/ch_dxl5912d4b01mmx58fspc0000gq/T/pip-pip-egg-info-00mb03q5
         cwd: /private/var/folders/5v/ch_dxl5912d4b01mmx58fspc0000gq/T/pip-install-73u8bfbs/embedding-as-service_13c5a0df862943ec82ce0f3c3d1bcad2/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/5v/ch_dxl5912d4b01mmx58fspc0000gq/T/pip-install-73u8bfbs/embedding-as-service_13c5a0df862943ec82ce0f3c3d1bcad2/setup.py", line 6, in <module>
        with open('requirements.txt') as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/43/8a/6e0726f57546d29a799077d2168803350c54d641068fdc7ba7bacbd1cbed/embedding_as_service-0.0.2.tar.gz#sha256=6286d676d5983a9eefea052dd5fb8d8d75bd6603b50d3e80955bd2135e6e5c34 (from https://pypi.org/simple/embedding-as-service/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Using cached embedding_as_service-0.0.1.tar.gz (1.3 kB)
    ERROR: Command errored out with exit status 1:
     command: /Users/yukun/Documents/test/embedding/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/5v/ch_dxl5912d4b01mmx58fspc0000gq/T/pip-install-73u8bfbs/embedding-as-service_0985b926e11f4b7d828e4a230ed45d7e/setup.py'"'"'; __file__='"'"'/private/var/folders/5v/ch_dxl5912d4b01mmx58fspc0000gq/T/pip-install-73u8bfbs/embedding-as-service_0985b926e11f4b7d828e4a230ed45d7e/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/5v/ch_dxl5912d4b01mmx58fspc0000gq/T/pip-pip-egg-info-6h629r6s
         cwd: /private/var/folders/5v/ch_dxl5912d4b01mmx58fspc0000gq/T/pip-install-73u8bfbs/embedding-as-service_0985b926e11f4b7d828e4a230ed45d7e/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/5v/ch_dxl5912d4b01mmx58fspc0000gq/T/pip-install-73u8bfbs/embedding-as-service_0985b926e11f4b7d828e4a230ed45d7e/setup.py", line 6, in <module>
        with open('requirements.txt') as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/ac/fa/691d432d0c2a42929dccfd04b3d898a1ea5210a2aecf5282a1bb9647f443/embedding_as_service-0.0.1.tar.gz#sha256=1091c5db093f1c1c24e850a3f50eb774b20795849d0183e4af49e7d39fbf6cb9 (from https://pypi.org/simple/embedding-as-service/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Cannot install embedding-as-service==0.0.4, embedding-as-service==0.0.5, embedding-as-service==0.0.6, embedding-as-service==0.0.7, embedding-as-service==0.0.8, embedding-as-service==0.0.9, embedding-as-service==0.1.0, embedding-as-service==0.2.0, embedding-as-service==0.3.0, embedding-as-service==0.4.0, embedding-as-service==0.5.0, embedding-as-service==0.6.0, embedding-as-service==0.7.0, embedding-as-service==0.8.0, embedding-as-service==0.9.0, embedding-as-service==1.0.0, embedding-as-service==1.3.0, embedding-as-service==1.4.0, embedding-as-service==1.5.0, embedding-as-service==1.6.0, embedding-as-service==2.0.0 and embedding-as-service==2.0.1 because these package versions have conflicting dependencies.

The conflict is caused by:
    embedding-as-service 2.0.1 depends on sentencepiece==0.1.85
    embedding-as-service 2.0.0 depends on sentencepiece==0.1.85
    embedding-as-service 1.6.0 depends on sentencepiece==0.1.85
    embedding-as-service 1.5.0 depends on tensorflow==1.15.0
    embedding-as-service 1.4.0 depends on tensorflow==1.14.0
    embedding-as-service 1.3.0 depends on tensorflow==1.14.0
    embedding-as-service 1.0.0 depends on tensorflow==1.14.0
    embedding-as-service 0.9.0 depends on tensorflow==1.14.0
    embedding-as-service 0.8.0 depends on tensorflow==1.14.0
    embedding-as-service 0.7.0 depends on tensorflow==1.14.0
    embedding-as-service 0.6.0 depends on tensorflow==1.14.0
    embedding-as-service 0.5.0 depends on tensorflow==1.14.0
    embedding-as-service 0.4.0 depends on sentencepiece==0.1.82
    embedding-as-service 0.3.0 depends on sentencepiece==0.1.82
    embedding-as-service 0.2.0 depends on sentencepiece==0.1.82
    embedding-as-service 0.1.0 depends on sentencepiece==0.1.82
    embedding-as-service 0.0.9 depends on sentencepiece==0.1.82
    embedding-as-service 0.0.8 depends on sentencepiece==0.1.82
    embedding-as-service 0.0.7 depends on sentencepiece==0.1.82
    embedding-as-service 0.0.6 depends on sentencepiece==0.1.82
    embedding-as-service 0.0.5 depends on sentencepiece==0.1.82
    embedding-as-service 0.0.4 depends on sentencepiece==0.1.82

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies
WARNING: You are using pip version 21.2.4; however, version 21.3.1 is available.
You should consider upgrading via the '/Users/yukun/Documents/test/embedding/bin/python -m pip install --upgrade pip' command.
(embedding) yukun@HOME-DEL-C02G23S0Q05N embedding % /Users/yukun/Documents/test/embedding/bin/python -m pip install --upgrade pip
Requirement already satisfied: pip in ./lib/python3.9/site-packages (21.2.4)
Collecting pip
  Using cached pip-21.3.1-py3-none-any.whl (1.7 MB)
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 21.2.4
    Uninstalling pip-21.2.4:
      Successfully uninstalled pip-21.2.4
Successfully installed pip-21.3.1
(embedding) yukun@HOME-DEL-C02G23S0Q05N embedding % pip install embedding-as-service
Collecting embedding-as-service
  Using cached embedding_as_service-2.0.1-py2.py3-none-any.whl (140 kB)
  Using cached embedding_as_service-2.0.0-py3-none-any.whl (140 kB)
Collecting requests==2.21.0
  Using cached requests-2.21.0-py2.py3-none-any.whl (57 kB)
Collecting embedding-as-service
  Using cached embedding_as_service-1.6.0-py3-none-any.whl (138 kB)
  Using cached embedding_as_service-1.5.0-py3-none-any.whl (137 kB)
Collecting tensorflow-hub==0.4.0
  Using cached tensorflow_hub-0.4.0-py2.py3-none-any.whl (75 kB)
Collecting bert-tensorflow==1.0.1
  Using cached bert_tensorflow-1.0.1-py2.py3-none-any.whl (67 kB)
Collecting embedding-as-service
  Using cached embedding_as_service-1.4.0-py3-none-any.whl (137 kB)
  Using cached embedding_as_service-1.3.0-py3-none-any.whl (130 kB)
  Using cached embedding_as_service-1.0.0-py3-none-any.whl (129 kB)
  Using cached embedding_as_service-0.9.0-py3-none-any.whl (129 kB)
  Using cached embedding_as_service-0.8.0-py3-none-any.whl (129 kB)
  Using cached embedding_as_service-0.7.0-py3-none-any.whl (128 kB)
  Using cached embedding_as_service-0.6.0-py3-none-any.whl (128 kB)
  Using cached embedding_as_service-0.5.0-py3-none-any.whl (128 kB)
  Using cached embedding_as_service-0.4.0-py3-none-any.whl (127 kB)
  Using cached embedding_as_service-0.3.0-py3-none-any.whl (127 kB)
  Using cached embedding_as_service-0.2.0-py3-none-any.whl (127 kB)
  Using cached embedding_as_service-0.1.0-py3-none-any.whl (127 kB)
  Using cached embedding_as_service-0.0.9-py3-none-any.whl (127 kB)
  Using cached embedding_as_service-0.0.8-py3-none-any.whl (127 kB)
  Using cached embedding_as_service-0.0.7-py3-none-any.whl (127 kB)
  Using cached embedding_as_service-0.0.6-py3-none-any.whl (125 kB)
  Using cached embedding_as_service-0.0.5-py3-none-any.whl (125 kB)
  Using cached embedding_as_service-0.0.4-py3-none-any.whl (125 kB)
  Using cached embedding_as_service-0.0.3.tar.gz (101 kB)
  Preparing metadata (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /Users/yukun/Documents/test/embedding/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/5v/ch_dxl5912d4b01mmx58fspc0000gq/T/pip-install-t876_3v6/embedding-as-service_9c3bc610ae584bef9a324574d470b92f/setup.py'"'"'; __file__='"'"'/private/var/folders/5v/ch_dxl5912d4b01mmx58fspc0000gq/T/pip-install-t876_3v6/embedding-as-service_9c3bc610ae584bef9a324574d470b92f/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/5v/ch_dxl5912d4b01mmx58fspc0000gq/T/pip-pip-egg-info-g730mipy
       cwd: /private/var/folders/5v/ch_dxl5912d4b01mmx58fspc0000gq/T/pip-install-t876_3v6/embedding-as-service_9c3bc610ae584bef9a324574d470b92f/
  Complete output (5 lines):
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/private/var/folders/5v/ch_dxl5912d4b01mmx58fspc0000gq/T/pip-install-t876_3v6/embedding-as-service_9c3bc610ae584bef9a324574d470b92f/setup.py", line 6, in <module>
      with open('requirements.txt') as f:
  FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
  ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/8e/db/6d4a90013dcaffce09a03ac33377fb7748ecc66bb87b71bf66e012dacb98/embedding_as_service-0.0.3.tar.gz#sha256=1d1acca51129707dee93cb47b43d67297c3ecfb0ae1e2d3f574c92bf0920320f (from https://pypi.org/simple/embedding-as-service/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Using cached embedding_as_service-0.0.2.tar.gz (1.3 kB)
  Preparing metadata (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /Users/yukun/Documents/test/embedding/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/5v/ch_dxl5912d4b01mmx58fspc0000gq/T/pip-install-t876_3v6/embedding-as-service_024540b978614d36ad90bfed03d50e3e/setup.py'"'"'; __file__='"'"'/private/var/folders/5v/ch_dxl5912d4b01mmx58fspc0000gq/T/pip-install-t876_3v6/embedding-as-service_024540b978614d36ad90bfed03d50e3e/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/5v/ch_dxl5912d4b01mmx58fspc0000gq/T/pip-pip-egg-info-cizztkhi
       cwd: /private/var/folders/5v/ch_dxl5912d4b01mmx58fspc0000gq/T/pip-install-t876_3v6/embedding-as-service_024540b978614d36ad90bfed03d50e3e/
  Complete output (5 lines):
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/private/var/folders/5v/ch_dxl5912d4b01mmx58fspc0000gq/T/pip-install-t876_3v6/embedding-as-service_024540b978614d36ad90bfed03d50e3e/setup.py", line 6, in <module>
      with open('requirements.txt') as f:
  FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
  ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/43/8a/6e0726f57546d29a799077d2168803350c54d641068fdc7ba7bacbd1cbed/embedding_as_service-0.0.2.tar.gz#sha256=6286d676d5983a9eefea052dd5fb8d8d75bd6603b50d3e80955bd2135e6e5c34 (from https://pypi.org/simple/embedding-as-service/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Using cached embedding_as_service-0.0.1.tar.gz (1.3 kB)
  Preparing metadata (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /Users/yukun/Documents/test/embedding/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/5v/ch_dxl5912d4b01mmx58fspc0000gq/T/pip-install-t876_3v6/embedding-as-service_4eccda2f22bd44f49fe99bdf8fd68e18/setup.py'"'"'; __file__='"'"'/private/var/folders/5v/ch_dxl5912d4b01mmx58fspc0000gq/T/pip-install-t876_3v6/embedding-as-service_4eccda2f22bd44f49fe99bdf8fd68e18/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/5v/ch_dxl5912d4b01mmx58fspc0000gq/T/pip-pip-egg-info-o7y2ick6
       cwd: /private/var/folders/5v/ch_dxl5912d4b01mmx58fspc0000gq/T/pip-install-t876_3v6/embedding-as-service_4eccda2f22bd44f49fe99bdf8fd68e18/
  Complete output (5 lines):
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/private/var/folders/5v/ch_dxl5912d4b01mmx58fspc0000gq/T/pip-install-t876_3v6/embedding-as-service_4eccda2f22bd44f49fe99bdf8fd68e18/setup.py", line 6, in <module>
      with open('requirements.txt') as f:
  FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
  ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/ac/fa/691d432d0c2a42929dccfd04b3d898a1ea5210a2aecf5282a1bb9647f443/embedding_as_service-0.0.1.tar.gz#sha256=1091c5db093f1c1c24e850a3f50eb774b20795849d0183e4af49e7d39fbf6cb9 (from https://pypi.org/simple/embedding-as-service/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Cannot install embedding-as-service==0.0.4, embedding-as-service==0.0.5, embedding-as-service==0.0.6, embedding-as-service==0.0.7, embedding-as-service==0.0.8, embedding-as-service==0.0.9, embedding-as-service==0.1.0, embedding-as-service==0.2.0, embedding-as-service==0.3.0, embedding-as-service==0.4.0, embedding-as-service==0.5.0, embedding-as-service==0.6.0, embedding-as-service==0.7.0, embedding-as-service==0.8.0, embedding-as-service==0.9.0, embedding-as-service==1.0.0, embedding-as-service==1.3.0, embedding-as-service==1.4.0, embedding-as-service==1.5.0, embedding-as-service==1.6.0, embedding-as-service==2.0.0 and embedding-as-service==2.0.1 because these package versions have conflicting dependencies.

The conflict is caused by:
    embedding-as-service 2.0.1 depends on tensorflow==1.15.2
    embedding-as-service 2.0.0 depends on sentencepiece==0.1.85
    embedding-as-service 1.6.0 depends on sentencepiece==0.1.85
    embedding-as-service 1.5.0 depends on sentencepiece==0.1.82
    embedding-as-service 1.4.0 depends on tensorflow==1.14.0
    embedding-as-service 1.3.0 depends on tensorflow==1.14.0
    embedding-as-service 1.0.0 depends on tensorflow==1.14.0
    embedding-as-service 0.9.0 depends on tensorflow==1.14.0
    embedding-as-service 0.8.0 depends on tensorflow==1.14.0
    embedding-as-service 0.7.0 depends on tensorflow==1.14.0
    embedding-as-service 0.6.0 depends on tensorflow==1.14.0
    embedding-as-service 0.5.0 depends on tensorflow==1.14.0
    embedding-as-service 0.4.0 depends on sentencepiece==0.1.82
    embedding-as-service 0.3.0 depends on sentencepiece==0.1.82
    embedding-as-service 0.2.0 depends on sentencepiece==0.1.82
    embedding-as-service 0.1.0 depends on sentencepiece==0.1.82
    embedding-as-service 0.0.9 depends on sentencepiece==0.1.82
    embedding-as-service 0.0.8 depends on sentencepiece==0.1.82
    embedding-as-service 0.0.7 depends on sentencepiece==0.1.82
    embedding-as-service 0.0.6 depends on sentencepiece==0.1.82
    embedding-as-service 0.0.5 depends on sentencepiece==0.1.82
    embedding-as-service 0.0.4 depends on sentencepiece==0.1.82

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies

```

**Comment by amansrivastava17** [comment]
@ReichYang Sorry for being so late, we have fixed it in the new release for `3.0.0` version.
